### PR TITLE
Move source code to /src

### PR DESCRIPTION
**Pull request by szepeviktor**
And fix PHPDoc blocks

@yaquawa

### CODE REVIEW

**Comment by szepeviktor** [comment]
You can pursue robust code with

```bash
vendor/bin/phpstan analyze -c vendor/szepeviktor/phpstan-wordpress/extension.neon -l 5 src/
```

**Comment by szepeviktor** [comment]
@yaquawa Any comment?

**Comment by yaquawa** [comment]
@szepeviktor This project is base on WordPress, it's hard to write tests. So I decide to keep as it.

**Comment by szepeviktor** [comment]
Okay.

**Pull request closed without merging**
